# Generated by Django 5.0.4 on 2024-05-04 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Desk',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=20)),
                ('number', models.PositiveIntegerField()),
                (
                    'status',
                    models.CharField(
                        choices=[('AVAILABLE', 'AVAILABLE'), ('RESERVED', 'RESERVED')],
                        default='AVAILABLE',
                        max_length=15,
                    ),
                ),
                (
                    'type',
                    models.CharField(
                        choices=[
                            ('small_desk', 'small_desk'),
                            ('narrow_desk', 'narrow_desk'),
                            ('medium_desk', 'medium_desk'),
                            ('large_desk', 'large_desk'),
                        ],
                        max_length=15,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('number', models.PositiveIntegerField()),
                (
                    'status',
                    models.CharField(
                        choices=[('AVAILABLE', 'AVAILABLE'), ('RESERVED', 'RESERVED')],
                        default='AVAILABLE',
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=20)),
                ('number', models.PositiveIntegerField()),
                ('max_amount_of_people', models.PositiveIntegerField()),
                (
                    'status',
                    models.CharField(
                        choices=[('AVAILABLE', 'AVAILABLE'), ('RESERVED', 'RESERVED')],
                        default='AVAILABLE',
                        max_length=10,
                    ),
                ),
                (
                    'type',
                    models.CharField(
                        choices=[
                            ('red_room', 'red_room'),
                            ('yellow_room', 'yellow_room'),
                            ('green_room', 'green_room'),
                            ('blue_room', 'blue_room'),
                        ],
                        max_length=15,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                (
                    'description',
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    'type',
                    models.CharField(
                        choices=[
                            ('DESK', 'DESK'),
                            ('ROOM', 'ROOM'),
                            ('PARKING', 'PARKING'),
                        ],
                        max_length=35,
                    ),
                ),
                (
                    'desk',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='reservations',
                        to='reservations.desk',
                    ),
                ),
                (
                    'parking',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='reservations',
                        to='reservations.parking',
                    ),
                ),
                (
                    'person',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='reservations',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'room',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='reservations',
                        to='reservations.room',
                    ),
                ),
            ],
        ),
    ]
