# Generated by Django 4.1.4 on 2023-03-22 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(),
                ),
                ("end_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("DESK", "DESK"),
                            ("ROOM", "ROOM"),
                            ("PARKING", "PARKING"),
                        ],
                        max_length=35,
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("number", models.PositiveIntegerField()),
                ("max_amount_of_people", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "AVAILABLE"),
                            ("RESERVED", "RESERVED"),
                            ("OCCUPIED", "OCCUPIED"),
                        ],
                        default="AVAILABLE",
                        max_length=10,
                    ),
                ),
                (
                    "reservation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room",
                        to="reservations.reservation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Parking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                ("floor", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "AVAILABLE"),
                            ("RESERVED", "RESERVED"),
                            ("OCCUPIED", "OCCUPIED"),
                        ],
                        default="AVAILABLE",
                        max_length=10,
                    ),
                ),
                (
                    "reservation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parking",
                        to="reservations.reservation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Desk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("number", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "AVAILABLE"),
                            ("RESERVED", "RESERVED"),
                            ("OCCUPIED", "OCCUPIED"),
                        ],
                        default="AVAILABLE",
                        max_length=15,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("small_desk", "small_desk"),
                            ("narrow_desk", "narrow_desk"),
                            ("medium_desk", "medium_desk"),
                            ("large_desk", "large_desk"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "reservation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="desk",
                        to="reservations.reservation",
                    ),
                ),
            ],
        ),
    ]
