# Generated by Django 5.1.1 on 2025-03-24 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desk',
            name='name',
            field=models.CharField(help_text='Name identifier for the desk', max_length=20),
        ),
        migrations.AlterField(
            model_name='desk',
            name='number',
            field=models.PositiveIntegerField(help_text='Unique desk number'),
        ),
        migrations.AlterField(
            model_name='desk',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'AVAILABLE'), ('RESERVED', 'RESERVED')], default='AVAILABLE', help_text='Current status of the desk', max_length=15),
        ),
        migrations.AlterField(
            model_name='desk',
            name='type',
            field=models.CharField(choices=[('small_desk', 'small_desk'), ('narrow_desk', 'narrow_desk'), ('medium_desk', 'medium_desk'), ('large_desk', 'large_desk')], help_text='Size/type designation of the desk', max_length=15),
        ),
        migrations.AlterField(
            model_name='parking',
            name='number',
            field=models.PositiveIntegerField(help_text='Unique parking spot number'),
        ),
        migrations.AlterField(
            model_name='parking',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'AVAILABLE'), ('RESERVED', 'RESERVED')], default='AVAILABLE', help_text='Current status of the parking spot', max_length=10),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the reservation was created'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='description',
            field=models.CharField(blank=True, help_text='Optional description for the reservation', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='desk',
            field=models.ForeignKey(blank=True, help_text='Associated desk for the reservation (if desk type)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reservations.desk'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end_date',
            field=models.DateField(help_text='End date of the reservation'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='parking',
            field=models.ForeignKey(blank=True, help_text='Associated parking spot for the reservation (if parking type)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reservations.parking'),
        ),
    ]
