# Generated by Django 4.1.4 on 2023-01-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desk',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'AVAILABLE'), ('RESERVED', 'RESERVED'), ('OCCUPIED', 'OCCUPIED')], default='AVAILABLE', max_length=10),
        ),
        migrations.AlterField(
            model_name='parking',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'AVAILABLE'), ('RESERVED', 'RESERVED'), ('OCCUPIED', 'OCCUPIED')], default='AVAILABLE', max_length=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'AVAILABLE'), ('RESERVED', 'RESERVED'), ('OCCUPIED', 'OCCUPIED')], default='AVAILABLE', max_length=10),
        ),
    ]
