# Generated by Django 5.1.1 on 2025-03-24 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_desk_name_alter_desk_number_alter_desk_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='person',
            field=models.ForeignKey(help_text='User who made the reservation', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(blank=True, help_text='Associated room for the reservation (if room type)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reservations.room'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_date',
            field=models.DateField(help_text='Start date of the reservation'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='title',
            field=models.CharField(blank=True, help_text='Optional title for the reservation', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='type',
            field=models.CharField(choices=[('DESK', 'DESK'), ('ROOM', 'ROOM'), ('PARKING', 'PARKING')], help_text='Type of reservation (desk, room, or parking)', max_length=35),
        ),
        migrations.AlterField(
            model_name='room',
            name='max_amount_of_people',
            field=models.PositiveIntegerField(help_text='Maximum number of people allowed in the room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(help_text='Name identifier for the room', max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.PositiveIntegerField(help_text='Unique room number'),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'AVAILABLE'), ('RESERVED', 'RESERVED')], default='AVAILABLE', help_text='Current status of the room', max_length=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('red_room', 'red_room'), ('yellow_room', 'yellow_room'), ('green_room', 'green_room'), ('blue_room', 'blue_room')], help_text='Type/color designation of the room', max_length=15),
        ),
    ]
