# Generated by Django 4.1.4 on 2023-03-23 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0002_alter_desk_reservation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="desk",
            name="reservation",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="reservations.reservation",
            ),
        ),
    ]
