# Generated by Django 5.1.1 on 2025-06-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_alter_reservation_person_alter_reservation_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desk',
            name='number',
            field=models.PositiveIntegerField(help_text='Unique desk number', unique=True),
        ),
    ]
