# Generated by Django 4.1.4 on 2023-03-23 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0003_alter_desk_reservation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="desk",
            name="reservation",
        ),
        migrations.RemoveField(
            model_name="parking",
            name="reservation",
        ),
        migrations.RemoveField(
            model_name="room",
            name="reservation",
        ),
        migrations.AddField(
            model_name="reservation",
            name="desk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="reservations.desk",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="parking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="reservations.parking",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="reservations.room",
            ),
        ),
    ]
