# Generated by Django 5.1.1 on 2025-06-01 19:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_alter_desk_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(condition=models.Q(('desk__isnull', False)), fields=('desk', 'start_date', 'end_date'), name='unique_desk_reservation_per_period'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(condition=models.Q(('room__isnull', False)), fields=('room', 'start_date', 'end_date'), name='unique_room_reservation_per_period'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(condition=models.Q(('parking__isnull', False)), fields=('parking', 'start_date', 'end_date'), name='unique_parking_reservation_per_period'),
        ),
    ]
