# Generated by Django 4.1.4 on 2023-03-23 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "reservations",
            "0004_remove_desk_reservation_remove_parking_reservation_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="parking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations_cxz",
                to="reservations.parking",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations_xyz",
                to="reservations.room",
            ),
        ),
    ]
