# Generated by Django 4.1.4 on 2023-03-23 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0005_alter_reservation_parking_alter_reservation_room"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="parking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="reservations.parking",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="reservations.room",
            ),
        ),
    ]
