# Generated by Django 4.1.4 on 2023-03-29 17:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0006_alter_reservation_parking_alter_reservation_room"),
    ]

    operations = []
