# Generated by Django 4.1.4 on 2023-03-29 17:28

from django.db import migrations


def create_desks(apps, schema_editor):
    Desk = apps.get_model('reservations', 'Desk')
    for num in range(1, 31):
        Desk.objects.create(
            name="Desk",
            type="small_desk",
            number=num,
        )



class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0006_alter_reservation_parking_alter_reservation_room"),
    ]

    operations = [
        migrations.RunPython(create_desks),
    ]
