# Generated by Django 4.1.4 on 2023-03-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0007_auto_20230329_1928"),
    ]

    operations = [
        migrations.AlterField(
            model_name="desk",
            name="status",
            field=models.CharField(
                choices=[("AVAILABLE", "AVAILABLE"), ("RESERVED", "RESERVED")],
                default="AVAILABLE",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="parking",
            name="status",
            field=models.CharField(
                choices=[("AVAILABLE", "AVAILABLE"), ("RESERVED", "RESERVED")],
                default="AVAILABLE",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="status",
            field=models.CharField(
                choices=[("AVAILABLE", "AVAILABLE"), ("RESERVED", "RESERVED")],
                default="AVAILABLE",
                max_length=10,
            ),
        ),
    ]
