# Generated by Django 4.1.4 on 2023-09-20 17:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0008_alter_desk_status_alter_parking_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parking",
            name="floor",
        ),
    ]
