# Generated by Django 4.1.4 on 2023-10-04 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reservations", "0009_remove_parking_floor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="start_date",
            field=models.DateField(help_text="date when reservations began"),
        ),
    ]
