# Generated by Django 4.1.4 on 2023-12-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0011_room_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="type",
            field=models.CharField(
                choices=[
                    ("red_room", "red_room"),
                    ("yellow_room", "yellow_room"),
                    ("green_room", "green_room"),
                    ("blue_room", "blue_room"),
                ],
                default="blue_room",
                max_length=15,
            ),
            preserve_default=False,
        ),
    ]
