# Generated by Django 4.1.4 on 2023-08-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_account_username_alter_account_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="password",
            field=models.CharField(max_length=255),
        ),
    ]
